version: 2
jobs:
  checkout_code:
    docker:
      - image: ubuntu:16.04
    working_directory: ~/roller
    steps:
      - run:
          name: Install essential packages
          command: |
            apt-get update && apt-get install -y ca-certificates git
      - checkout
      - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/roller

  build_test_and_deploy:
    # note: doesn't run the deploy to dockerhub step
    docker:
      - image: ubuntu:16.04
    working_directory: ~/roller
    steps:
      - run:
          name: Install essential packages
          command: |
            apt-get update && apt-get install -y ca-certificates curl make

      - restore_cache:
          keys:
            - v1-repo-{{ .Environment.CIRCLE_SHA1 }}

      - run:
          name: Install Docker
          command: |
            set -x
            VER="17.09.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin

      - run:
          name: Install Docker Compose
          command: |
            set -x
            curl -L https://github.com/docker/compose/releases/download/1.16.0/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
            chmod +x /usr/local/bin/docker-compose

      - setup_remote_docker:
          version: 17.09.0-ce

      - run:
          name: Create version.json
          working_directory: ~/roller
          command: |
            # create a version.json per https://github.com/mozilla-services/Dockerflow/blob/master/docs/version_object.md
            printf '{"commit":"%s","version":"%s","source":"https://github.com/%s/%s","build":"%s"}\n' \
            "$CIRCLE_SHA1" \
            "$CIRCLE_TAG" \
            "$CIRCLE_PROJECT_USERNAME" \
            "$CIRCLE_PROJECT_REPONAME" \
            "$CIRCLE_BUILD_URL" > version.json

      - run:
          name: Build Docker images
          working_directory: ~/roller
          command: |
            docker info
            cp .env-dist .env
            # build roller containers
            make build

      - run:
          name: Run tests
          working_directory: ~/roller
          command: |
            cp .env-dist .env
            make test

      - store_artifacts:
          path: ~/roller/coverage.xml
          destination: coverage.xml

      - store_artifacts:
          path: ~/roller/htmlcov
          destination: htmlcov/


workflows:
  version: 2

  # workflow jobs are _not_ run in tag builds by default
  # we use filters to whitelist jobs that should be run for tags

  # workflow jobs are run in _all_ branch builds by default
  # we use filters to blacklist jobs that shouldn't be run for a branch

  # see: https://circleci.com/docs/2.0/workflows/#git-tag-job-execution

  build-test-deploy:
    jobs:
      - checkout_code:
          filters:
            tags:
              only: /.*/
      - build_test_and_deploy:
          requires:
            - checkout_code
          filters:
            tags:
              only: /.*/
