# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 16:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('worker_id', models.CharField(max_length=128)),
                ('task_name', models.CharField(choices=[('ping', 'ping'), ('reboot', 'reboot')], max_length=64)),
                ('task_id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=255)),
                ('ip', models.GenericIPAddressField()),
            ],
        ),
        migrations.CreateModel(
            name='TaskClusterWorker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tc_provisioner_id', models.CharField(blank=True, max_length=128)),
                ('tc_worker_type', models.CharField(blank=True, max_length=128)),
                ('tc_worker_group', models.CharField(blank=True, max_length=128)),
                ('tc_worker_id', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='machine',
            name='workers',
            field=models.ManyToManyField(related_name='machines', to='api.TaskClusterWorker'),
        ),
        migrations.AddField(
            model_name='job',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Machine'),
        ),
        migrations.AddField(
            model_name='job',
            name='tc_worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.TaskClusterWorker'),
        ),
    ]
